[project]
name = "buddy"
version = "0.1.0"
description = "An autonomous LLM agent with comprehensive system tools"
authors = [
    {name = "Sebastian Hirt", email = "sebastian@hirts.de"},
]

requires-python = ">=3.13"

dependencies = [
    "langchain-core>=0.3.47",
    "rich>=10.0.0",
    "python-dotenv>=1.0.1",
    "langgraph>=0.3.18",
    "langchain-openai>=0.3.9",
    "langchain-community>=0.3.20",
    "duckduckgo-search>=7.5.3",
    "prompt-toolkit>=3.0.50",
    "tiktoken>=0.9.0",
    "bs4>=0.0.2",
]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.13",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venv = ".venv"
venvPath = "."

[tool.hatch.build.targets.wheel]
packages = ["buddy"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.ruff]
line-length = 88
target-version = "py313"
lint.select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "ANN", # Type annotations
]
lint.ignore = [
    "E501",  # Line too long (handled by formatter)
    "D100", # Top of module missing docstring
    "D101",
    "D103",
    "D213",
    "D203",
    "D107", # docstring in init
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

