services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.6.36
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - openwebui:/app/backend/data
    restart: unless-stopped

volumes:
  openwebui:

